### ISSUE TITLE
Permission denied on the Wifi Pineapple Nano

### ISSUE THREAD

**Issue by kleo** [adde88/krackattacks-pineapple#1]
Testing krack-test-client.py on a freshly reset Wifi Pineapple Nano.

```
root@Pineapple:/sd/krackattacks-pineapple/krackattack# ./krack-test-client.py --tptk
[17:54:13] Note: disable Wi-Fi in network manager & disable hardware encryption. Both may interfere with this script.
[17:54:14] Starting hostapd ...
Traceback (most recent call last):
  File "./krack-test-client.py", line 620, in <module>
    attack.run(test_grouphs=test_grouphs, test_tptk=test_tptk)
  File "./krack-test-client.py", line 483, in run
    + sys.argv[1:])
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```
```
-rwxrwxrwx    1 root     root         25602 Dec 20 17:49 krack-test-client.py
```

wlan1 not being used on anything. Set up everything just fine, using an sdcard. Python also symlinked and compiled from the sdcard. Will test out later using a mounted flashdrive.

**Comment by kleo** [comment]
Mounted a flashdrive, setup from scratch. krack-test-client.py ran really well, also discovered my device was vulnerable :(

**Comment by Rinilyn** [comment]
I'm having the same issue,using the nano with firmware 2.3.2.
installing scapy gives this error:

root@Pineapple:~# pip install scapy
Traceback (most recent call last):
  File "/usr/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/setuptools-7.0-py2.7.egg/pkg_resources.py", line 35, in <module>
ImportError: No module named email.parser

When i try to go to the file,there is a permission denied error. Can we do this without the flash drive?
